Improve deploy script for Wordpress site
- Unify the logic in setup and teardown scripts so that it can handle
  setups in which both Wordpress site and MySQL server are on same host

diff --git a/deploy/teardown-wordpress b/deploy/teardown-wordpress
--- a/deploy/teardown-wordpress
+++ b/deploy/teardown-wordpress
@@ -2,11 +2,12 @@
 
 # Remotely teardown Wordpress website, along with its MySQL database and user
 
-[[ $# != 3 ]] && >&2 echo "Usage: $0 WEBSITE_NAME WP_DEST DB_DEST" && exit 1
+[[ $# -lt 2 || $# -gt 3 ]] && >&2 echo "Usage: $0 WEBSITE_NAME WP_DEST [DB_DEST]" && exit 1
 
 website_name="$1" ; shift
 wp_dest="$1" ; shift
 db_dest="$1" ; shift
+[[ $db_dest = "" ]] && db_dest=$wp_dest
 
 mysql_port=3306
 
@@ -14,15 +15,20 @@ echo "INFO [$(date)]: Begin teardown of Wordpress website and its MySQL database
 
 ## Get private IP address values of DB server and Wordpress server
 
-wordpress_private_ip=$(ssh $wp_dest "private-ip" | cut -f1 -d/)
-if [[ $wordpress_private_ip = "" ]]; then
-	>&2 echo "Error: Cannot retrieve private IP of Wordpress server."
-	exit 1
-fi
-mysqld_private_ip=$(ssh $db_dest "private-ip" | cut -f1 -d/)
-if [[ $mysqld_private_ip = "" ]]; then
-	>&2 echo "Error: Cannot retrieve private IP of MySQL server."
-	exit 1
+if [[ $db_dest != $wp_dest ]]; then
+	wordpress_private_ip=$(ssh $wp_dest "private-ip" | cut -f1 -d/)
+	if [[ $wordpress_private_ip = "" ]]; then
+		>&2 echo "Error: Cannot retrieve private IP of Wordpress server."
+		exit 1
+	fi
+	mysqld_private_ip=$(ssh $db_dest "private-ip" | cut -f1 -d/)
+	if [[ $mysqld_private_ip = "" ]]; then
+		>&2 echo "Error: Cannot retrieve private IP of MySQL server."
+		exit 1
+	fi
+else
+	wordpress_private_ip=localhost
+	mysqld_private_ip=localhost
 fi
 
 
@@ -64,8 +70,10 @@ echo "Success!"
 
 
 #* Do not remove firewall rule for this Wordpress-MySQL port connection, in case there are other active Wordpress connections
-#echo "INFO: Remove MySQL client connections from private IP address of Wordpress server"
-#ssh $db_dest "sudo firewall-remove-rule $mysql_port $wordpress_private_ip"
+#if [[ $db_dest != $wp_dest ]]; then
+#    echo "INFO: Remove MySQL client connections from private IP address of Wordpress server"
+#    ssh $db_dest "sudo firewall-remove-rule $mysql_port $wordpress_private_ip"
+#fi
 
 
 # Remove traces of Wordpress site on Wordpress server
diff --git a/deploy/wordpress b/deploy/wordpress
--- a/deploy/wordpress
+++ b/deploy/wordpress
@@ -1,31 +1,44 @@
 #!/usr/bin/env bash
 
-# Remotely set up Wordpress website, connecting it to an external MySQL server
+# Remotely set up Wordpress website, connecting it to (external) MySQL server
 
-[[ $# != 3 ]] && >&2 echo "Usage: $0 WEBSITE_NAME WP_DEST DB_DEST" && exit 1
+[[ $# -lt 2 || $# -gt 3 ]] && >&2 echo "Usage: $0 WEBSITE_NAME WP_DEST [DB_DEST]" && exit 1
 
 website_name="$1" ; shift
 wp_dest="$1" ; shift
 db_dest="$1" ; shift
+[[ $db_dest = "" ]] && db_dest=$wp_dest
 
 mysql_port=3306
 
 
-echo "INFO [$(date)]: Begin provision of Wordpress website connected to MySQL database server on separate host..."
-
-
-## Get private IP address values of DB server and Wordpress server
-
-wordpress_private_ip=$(ssh $wp_dest "private-ip" | cut -f1 -d/)
-if [[ $wordpress_private_ip = "" ]]; then
-	>&2 echo "Error: Cannot retrieve private IP of Wordpress server."
-	exit 1
+## Check whether to set up connection to local MySQL server
+if [[ $db_dest = $wp_dest ]]; then
+	ssh $wp_dest "command -v mysqld >/dev/null"
+	test $? != 0 && >&2 echo "Error: MySQL server not found on target server." && exit 1
+	echo "INFO [$(date)]: Will set up Wordpress website connected to MySQL database server on same host..."
+else
+	echo "INFO [$(date)]: Begin provision of Wordpress website connected to MySQL database server on separate host..."
 fi
 
-mysqld_private_ip=$(ssh $db_dest "private-ip" | cut -f1 -d/)
-if [[ $mysqld_private_ip = "" ]]; then
-	>&2 echo "Error: Cannot retrieve private IP of MySQL server."
-	exit 1
+
+## Get values for server hosts
+if [[ $db_dest != $wp_dest ]]; then
+	### Get private IP address values of DB server and Wordpress server
+	wordpress_host=$(ssh $wp_dest "private-ip" | cut -f1 -d/)
+	if [[ $wordpress_host = "" ]]; then
+		>&2 echo "Error: Cannot retrieve private IP of Wordpress server."
+		exit 1
+	fi
+
+	mysql_host=$(ssh $db_dest "private-ip" | cut -f1 -d/)
+	if [[ $mysql_host = "" ]]; then
+		>&2 echo "Error: Cannot retrieve private IP of MySQL server."
+		exit 1
+	fi
+else
+	wordpress_host=localhost
+	mysql_host=localhost
 fi
 
 
@@ -49,10 +62,9 @@ ssh $db_dest "
 	mysql -uroot -p\$mysql_root_pw -e \"
 		CREATE DATABASE $db_name
 			DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-		CREATE USER '$db_user'@'$wordpress_private_ip'
-			IDENTIFIED BY '$db_password_escaped';
+		CREATE USER '$db_user'@'$wordpress_host' IDENTIFIED BY '$db_password_escaped';
 		GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX
-			ON $db_name.* TO '$db_user'@'$wordpress_private_ip';
+			ON $db_name.* TO '$db_user'@'$wordpress_host';
 		FLUSH PRIVILEGES;
 		\" 2>/tmp/mysql-error
 	test \$? != 0 && >&2 cat /tmp/mysql-error && exit 1
@@ -68,12 +80,12 @@ ssh $db_dest "
 
 	### Confirm that user can connect from private IP address of Wordpress server
 	if ! mysql -uroot -p\$mysql_root_pw -Bse 'SELECT Host, User FROM mysql.user;' \
-		2>/dev/null | grep $db_user | grep -q $wordpress_private_ip
+		2>/dev/null | grep $db_user | grep -q $wordpress_host
 	then
 		>&2 echo 'Error: User was not created.'
 		exit 1
 	fi
-	echo 'INFO: User '$db_user'@'$wordpress_private_ip' was created!'
+	echo 'INFO: User '$db_user'@'$wordpress_host' was created!'
 	"
 test $? != 0 && >&2 echo "Failed... 😔" && exit 1
 echo "Success!"
@@ -93,7 +105,7 @@ ssh $wp_dest "
 	echo \"INFO: Saving credentials for database to file: '~/.credentials/mysql/$db_name'\"
 	cat >> ~/.credentials/mysql/$db_name <<-EOF
 		# Credentials for MySQL server
-		db_host=$mysqld_private_ip
+		db_host=$mysql_host
 		db_name=$db_name
 		db_user=$db_user
 		db_password='$db_password_escaped'
@@ -101,8 +113,10 @@ ssh $wp_dest "
 	"
 
 
-echo "INFO: Allow MySQL client connections from private IP address of Wordpress server"
-ssh $db_dest "sudo firewall-add-rule $mysql_port $wordpress_private_ip"
+if [[ $db_dest != $wp_dest ]]; then
+	echo "INFO: Allow MySQL client connections from private IP address of Wordpress server"
+	ssh $db_dest "sudo firewall-add-rule $mysql_port $wordpress_host"
+fi
 
 
 ## Confirm that we can query MySQL server from Wordpress server
