Wordpress to MySQL DB server on different hosts
- Add lots of error checking to the scripts

diff --git a/setup/db/mysql b/setup/db/mysql
--- a/setup/db/mysql
+++ b/setup/db/mysql
@@ -2,32 +2,54 @@
 
 # Create database for project
 
-[[ $db_name = "" ]] && >&2 echo "Error: Missing argument for \$db_name." && exit 1
-[[ $db_user = "" ]] && >&2 echo "Error: Missing argument for \$db_user." && exit 1
-[[ $db_password = "" ]] && >&2 echo "Error: Missing argument for \$db_password." && exit 1
+[[ $# != 1 ]] && >&2 echo "Usage: $0 DB_NAME" && exit 1
+
+db_name=$1 ; shift
+db_user=$db_name
+
+
+echo "INFO [$(date)]: Begin creation of MySQL database and user named '$db_name'."
+
+db_password="$(randpw)"
 
 
 ## Get password for root MySQL user
-mysql_root_pw=$(cat /home/$SUDO_USER/.credentials/mysql_root_pw)
-
+mysql_root_pw=$(cat /home/$USER/.credentials/mysql_root_pw)
 if [[ $mysql_root_pw = "" ]]; then
-	2>&1 echo "Missing password for root MySQL user in '/home/$SUDO_USER/.credentials/mysql_root_pw'!"
+	2>&1 echo "Missing password for root MySQL user in '/home/$USER/.credentials/mysql_root_pw'!"
 	exit 1
 fi
 
 
-## Create database and user
-echo "INFO: Creating database '$db_name' and user '$db_user'"
+## Store database credentials in file
+dir_db_credentials=/home/$USER/.credentials/mysql
+if [[ ! -d $dir_db_credentials ]]; then
+	mkdir -vp $dir_db_credentials
+	chmod -v 600 $dir_db_credentials
+fi
+echo "INFO: Saving credentials for database to file: '$dir_db_credentials/$db_name'"
+cat >> $dir_db_credentials/$db_name <<-EOF
+	db_host=localhost
+	db_name=$db_name
+	db_user=$db_user
+	db_password='$db_password'
+	EOF
+
+
+## Create database and user with privileges
+echo "INFO: Creating database '$db_name' and user '$db_user'..."
 mysql -uroot -p$mysql_root_pw -e "
 	CREATE DATABASE $db_name DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
 	CREATE USER '$db_user'@'localhost' IDENTIFIED BY '$db_password';
-	GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@'localhost';
+	GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX ON $db_name.*
+		TO '$db_user'@'localhost';
 	FLUSH PRIVILEGES;
-	"
+	" 2>/tmp/mysql-error
+test $? != 0 && >&2 cat /tmp/mysql-error && exit 1
 
 
 ## Query to confirm that newly created user can access database
-echo "INFO: Verifying that user can access database"
+echo "INFO: Verifying that the user can access database..."
 mysql -u$db_user -p$db_password $db_name -e '
 	status
 
@@ -35,8 +57,19 @@ mysql -u$db_user -p$db_password $db_name -e '
 	  `id` INT AUTO_INCREMENT,
 	  `name` VARCHAR(255),
 	  PRIMARY KEY (`id`)
-	)
-
+	);
 	INSERT INTO users (name) VALUES ("Adam");
 	INSERT INTO users (name) VALUES ("Eve");
-	'
+	' 2>/tmp/mysql-error
+test $? != 0 && >&2 cat /tmp/mysql-error && exit 1
+
+### Sample of SQL script with value substitution
+mysql -u$db_user -p$db_password $db_name -e "
+	INSERT INTO users (name) VALUES ('$USER');
+	SELECT * from users;
+	" 2>/tmp/mysql-error 1>/dev/null
+test $? != 0 && >&2 cat /tmp/mysql-error && exit 1
+
+
+echo "INFO [$(date)]: Success! Database '$db_name' has been setup."
+
diff --git a/setup/install/mysqld b/setup/install/mysqld
--- a/setup/install/mysqld
+++ b/setup/install/mysqld
@@ -80,24 +80,40 @@ expect eof
 EOF
 
 
-### Backup /var/lib/mysql/mysqld-auto.cnf
+### Password settings
+
+#### Backup /var/lib/mysql/mysqld-auto.cnf file
 [[ -f /var/lib/mysql/mysqld-auto.cnf ]] && sudo bak /var/lib/mysql/mysqld-auto.cnf
 
-### Set minimum password length
+#### Set minimum password length
 password_length=16
 echo "Set minimum password length to $password_length..."
 mysql -uroot -p$mysql_root_pw -e "
 	SET PERSIST validate_password.length = $password_length;
-	"
+	" 2>/dev/null
 
+#### Do not require multiple character types in passwords
+validate_password_policy=$(
+	mysql -uroot -p$mysql_root_pw -Bse " SELECT @@GLOBAL.validate_password.policy;" \
+		2>/dev/null
+	)
+if [[ $validate_password_policy != LOW ]]; then
+	mysql -uroot -p$mysql_root_pw -e "SET PERSIST validate_password.policy = 'LOW';" 2>/dev/null
+	if [[ $? = 0 ]]; then
+		echo "Set validate_password.policy = 'LOW'"
+	else
+		>&2 echo "Error: Did not successfully set validate_password.policy."
+	fi
+fi
 
-### Notes for security settings
-
-#### Do not require multiple character types
-#mysql -uroot -p$mysql_root_pw -e "
-#    SET PERSIST validate_password.policy = 'LOW';
-#    "
-
-#### Display system variables
+#### Note: To display records for MySQL server system variables starting with 'validate':
 #mysql -uroot -p$mysql_root_pw -e "SHOW VARIABLES LIKE 'validate%';"
+
+
+#### Add rule to firewall
+#* Currently not used. Instead, we open the firewall on a case-by-case basis
+#* (i.e. we open up the MySQL server port for each IP address that requires access)
+
+#sudo firewall-cmd --permanent --add-service=mysql
+#sudo firewall-cmd --reload
 
diff --git a/setup/web/wordpress b/setup/web/wordpress
--- a/setup/web/wordpress
+++ b/setup/web/wordpress
@@ -49,6 +49,15 @@ if ! command -v php >/dev/null; then
 	echo " DONE! [$(date)]"
 fi
 
+## Install MySQL client if not found
+if ! command -v mysql >/dev/null; then
+	[[ ! -d /var/log/setup/install ]] && mkdir -vp /var/log/setup/install
+	printf "INFO: Installing mysql..."
+	sudo dnf install -y mysql
+		2>&1 | tee /var/log/setup/install/mysql >/dev/null
+	echo " DONE! [$(date)]"
+fi
+
 
 # Main
 
@@ -61,34 +70,43 @@ html_dir=/var/www/$domain/html
 nginx_conf=/var/www/$domain/nginx.conf
 
 
-## Set up HTML website first
-$(dirname $0)/html $domain
+if [[ -d $project_dir ]]; then
+	>&2 echo "Error: Project directory '$project_dir' already exists. Aborting."
+	exit 1
+fi
 
 
-## Create database on localhost
+## Set up database connection, either to external server or create one on localhost
 
-### Store SQL credentials in file
 sql_friendly_name=$(echo $domain | tr "." "_")
 db_name="wp_$sql_friendly_name"
-db_user="$db_name"
-db_password="$(randpw)"
-db_host=localhost
 
-cat >> $project_dir/credentials.txt <<-EOF
+create_database() {
+	[[ ! -d /var/log/setup/db ]] && mkdir -vp /var/log/setup/db
+	su - $SUDO_USER -c "\"$(dirname $0)\"/../db/mysql $db_name" \
+		2>&1 | sudo tee /var/log/setup/db/mysql--$db_name
+	if test ${PIPESTATUS[0]} != 0; then
+		>&2 echo "INFO [$(date)]: Setup failed! 😧" && exit 1
+	fi
+}
 
-	# DOMAIN: $domain
+### Database server credentials
+db_credentials_file=/home/$SUDO_USER/.credentials/mysql/$db_name
+if [[ -f $db_credentials_file ]]; then
+	echo "INFO: Retrieving database credentials from file: '$db_credentials_file'"
+elif command -v mysqld >/dev/null; then
+	### If mysqld is found locally, then create locally-hosted MySQL database
+	echo "INFO: Creating database on local MySQL server..."
+	create_database
+else
+	>&2 echo "Error: No credentials found for database server."
+	exit 1
+fi
 
 
-	# SQL
-	db_name='$db_name'
-	db_user='$db_user'
-	db_password='$db_password'
-	db_host='$db_host'
-
-	EOF
-
-### Run SQL commands
-source "$(dirname $0)/../db/mysql"
+## Set up HTML website
+$(dirname $0)/html $domain
+test $? != 0 && >&2 echo "INFO [$(date)]: Setup failed! 😧" && exit 1
 
 
 ## Install Wordpress
@@ -100,7 +118,7 @@ downloads_dir=/home/$SUDO_USER/downloads
 [[ ! -d $downloads_dir ]] && mkdir -v $downloads_dir
 cd $downloads_dir
 
-if [[ ! -f wordpress.tgz ]] || find . -name wordpress.tgz -mmin +$((60*6)); then
+if [[ ! -f wordpress.tgz || $(find -name wordpress.tgz -mmin +$((60*6)) | wc -l) -gt 0 ]]; then
 	curl --output wordpress.tgz -L "https://wordpress.org/latest.tar.gz"
 fi
 
@@ -158,6 +176,7 @@ systemctl reload nginx
 
 
 ## Wordpress Configuration
+
 ## Automate the "famous five-minute WordPress installation"
 echo -e "\nAutomate the \"famous five-minute WordPress installation\"..."
 echo -e "\nSetting up wp-config.php..."
@@ -174,11 +193,13 @@ sleep 1  # Wait a sec for some breathing room
 # TODO: Ping server before submitting any data.
 
 echo "Set database credentials via POST request to /wp-admin/setup-config.php?step=2 ..."
+source $db_credentials_file
 password_encoded=$(php -r "echo urlencode('$db_password');")
 curl -si "https://$domain/wp-admin/setup-config.php?step=2" \
 	-XPOST \
 	--data "dbname=$db_name&uname=$db_user&pwd=$password_encoded&dbhost=$db_host&prefix=wp_&&submit=Submit" \
 	| head -1
+test $? != 0 && >&2 echo "INFO [$(date)]: Setup failed! 😧" && exit 1
 
 #### Alternative method to set db credentials and authentication keys and salt
 #cd $html_dir
@@ -257,6 +278,7 @@ curl -si "https://$domain/wp-admin/install.php?step=2" \
 	-H "Content-Type: application/x-www-form-urlencoded" \
 	--data "weblog_title=$website_title&user_name=$wp_user&admin_password=$password_encoded&admin_password2=$password_encoded&admin_email=$wp_user_email&Submit=Install+WordPress" \
 	| head -1
+test $? != 0 && >&2 echo "INFO [$(date)]: Setup failed! 😧" && exit 1
 
 
 ### Restore SELinux default labels to disallow server app from writing to system at root website directory
