Secure MySQL installation
- Automate steps of mysql_secure_installation using expect
- Create and store password for root MySQL user

diff --git a/setup/db/mysql b/setup/db/mysql
--- a/setup/db/mysql
+++ b/setup/db/mysql
@@ -6,7 +6,14 @@
 [[ $db_user = "" ]] && >&2 echo "Error: Missing argument for \$db_user." && exit 1
 [[ $db_password = "" ]] && >&2 echo "Error: Missing argument for \$db_password." && exit 1
 
+
+## Get password for root MySQL user
 mysql_root_pw=$(cat /home/$SUDO_USER/.credentials/mysql_root_pw)
+
+if [[ $mysql_root_pw = "" ]]; then
+	2>&1 echo "Missing password for root MySQL user in '/home/$SUDO_USER/.credentials/mysql_root_pw'!"
+	exit 1
+fi
 
 
 ## Create database and user
